#!/bin/sh
#bug fix for container restart
(rm /run/rsyslog.pid | true)

chmod 777 -R /var/lib/clamav/
if [ ! -f /var/lib/clamav/bytecode.cvd ]
then
#first run - get full virus databases
  freshclam
fi
freshclam -d -c 24
clamd
